when:
  - event: tag

steps:
  - name: bootstrap
    image: git.omni.ms/omnilium/toolbox:latest
    pull: true
    environment:
      REMOTE_USERNAME:
        from_secret: copyparty_user
      REMOTE_PASSWORD:
        from_secret: copyparty_password
    commands:
      - bash bootstrap.sh remote

  - name: archive
    image: mcr.microsoft.com/dotnet/sdk:9.0
    pull: true
    commands:
      - bash build.sh --target Archive --general-project DurableBetterProspecting --general-version ${CI_COMMIT_TAG}

  - name: release
    image: woodpeckerci/plugin-release:latest
    pull: true
    settings:
      api-key:
        from_secret: forgejo_release_key
      files:
        - out/*.zip
      draft: true
