when:
  - event: tag

matrix:
  PROJECT:
    - DurableBetterProspecting

steps:
  - name: bootstrap
    image: git.omni.ms/omnilium/toolbox:latest
    environment:
      REMOTE_USERNAME:
        from_secret: copyparty_user
      REMOTE_PASSWORD:
        from_secret: copyparty_password
    commands:
      - bash bootstrap.sh remote

  - name: archive
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - bash build.sh --target Archive --general-project ${PROJECT} --general-version ${CI_COMMIT_TAG}

  - name: release
    image: woodpeckerci/plugin-release:latest
    settings:
      api-key:
        from_secret: forgejo_release_key
      files:
        - out/*.zip
      draft: true
